package com.miara.cuentame.core.domain.validation

sealed class ValidationError(override val message: String) : Exception(message) {
    data object InvalidName : ValidationError("Name cannot be empty")
    data object DuplicateActiveName : ValidationError("An active record with this name already exists")
    data object InvalidDecimal : ValidationError("Invalid decimal value")
    data object InvalidUnitFactor : ValidationError("Unit factor must be greater than zero")
    data object IncompatibleUnitDimensions : ValidationError("Units must have the same dimension")
    data object MissingBaseUnitOption : ValidationError("Ingredient must have a base unit option")
    data object MultipleBaseUnitOptions : ValidationError("Ingredient cannot have more than one base unit option")
    data object InvalidBaseUnitFactor : ValidationError("Base unit option must have a factor of 1")
    data object InvalidDefaultUnitOption : ValidationError("Default option must belong to the correct ingredient")
    data object IngredientHasInventoryHistory : ValidationError("Cannot perform this action on an ingredient with movement history")
    data object IngredientBaseUnitImmutable : ValidationError("Base unit cannot be changed after creation")
    data object ArchivedReference : ValidationError("Cannot reference an archived record")
    data object RecordNotFound : ValidationError("The requested record was not found")
    data object IngredientNotFound : ValidationError("Ingredient not found")
    data object UnitOptionNotFound : ValidationError("Unit option not found")
    data object UnitOptionNameAlreadyExists : ValidationError("An option with this name already exists for this ingredient")
    data object BaseUnitOptionCannotBeModified : ValidationError("The base unit option cannot be modified")
    data object BaseUnitOptionCannotBeArchived : ValidationError("The base unit option cannot be archived")
    data object DefaultUnitOptionCannotBeArchived : ValidationError("A default count or purchase option cannot be archived")
    data object StandardUnitAlreadyAdded : ValidationError("This standard unit is already added as an option")
    data object InvalidStandardUnitFactor : ValidationError("The standard unit factor must match the system conversion")
    data object InvalidPackageQuantity : ValidationError("Quantity must be greater than zero")
    data object InvalidCurrencyCode : ValidationError("Invalid ISO currency code")

    // Onboarding and Setup Errors
    data object SetupAlreadyCompleted : ValidationError("Setup has already been completed")
    data object NoActiveInventoryArea : ValidationError("At least one active inventory area is required")
    data object UnsupportedLocale : ValidationError("Unsupported application locale")
    data object InvalidSetupState : ValidationError("Current setup state is invalid")
    data object FinalAreaCannotBeArchived : ValidationError("The last active area cannot be archived")
    data object OnboardingDraftCorrupted : ValidationError("The onboarding draft is corrupted and has been reset")
    data object UnsupportedOnboardingDraftVersion : ValidationError("The onboarding draft version is not supported")
    data object OnboardingDraftSaveFailed : ValidationError("Failed to save the onboarding draft")

    // Movement and Reversal Errors
    data object MovementNotFound : ValidationError("Movement not found")
    data object MovementAlreadyReversed : ValidationError("Movement has already been reversed")
    data object CannotReverseReversal : ValidationError("Cannot reverse a reversal movement")
    data object InvalidReversalReference : ValidationError("Invalid reversal reference")
    data object InvalidReversalQuantity : ValidationError("Reversal quantity must be the exact negative of the original")
    data object InvalidMovementSourceOperation : ValidationError("Invalid movement source operation")
    data object MovementOwnershipMismatch : ValidationError("Movement does not belong to the expected ingredient or area")
}
