package com.miara.cuentame.feature.sales
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.miara.cuentame.R
import com.miara.cuentame.app.ui.theme.AppSpacing
import com.miara.cuentame.core.designsystem.component.*
import com.miara.cuentame.core.designsystem.util.Formatters
import com.miara.cuentame.core.model.salesimport.*
import java.math.BigDecimal
import java.time.ZoneId
import java.time.format.*
private val dateFmt get()=DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM)
private val dateTimeFmt get()=DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM,FormatStyle.SHORT).withZone(ZoneId.systemDefault())
private val timeFmt get()=DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT).withZone(ZoneId.systemDefault())

@OptIn(ExperimentalMaterial3Api::class) @Composable fun SalesRoute(onBack:()->Unit,onImport:(String)->Unit,vm:SalesImportListViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle();val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){it?.let(vm::select)};val pick={picker.launch(arrayOf("application/json","text/json","text/plain"))};val snack=remember{SnackbarHostState()};val success=stringResource(R.string.sales_import_success)
 LaunchedEffect(s.success){if(s.success){snack.showSnackbar(success);vm.consumeSuccess()}}
 Scaffold(snackbarHost={AppSnackbarHost(snack)},topBar={TopAppBar(title={Text(stringResource(R.string.sales_title))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}})}){p->when{s.loading->Centered(p){CircularProgressIndicator()};s.noRestaurant->Centered(p){SalesErrorState(stringResource(R.string.sales_load_error))};else->LazyColumn(Modifier.padding(p).adaptiveContentWidth(960.dp),contentPadding=PaddingValues(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.md)){item{AppSectionHeader(stringResource(R.string.sales_history),subtitle=stringResource(R.string.sales_history_support),trailing={ImportButton(pick,!s.busy)})};if(s.imports.isEmpty())item{EmptySales(pick,!s.busy)}else items(s.imports,key={it.exportId}){x->SalesHistoryCard(x){onImport(x.exportId)}};if(s.busy&&s.prepared==null)item{BusyRow()}}}}
 s.prepared?.let{SalesImportPreview(it,s.busy,vm::dismiss,vm::confirm)}
 s.duplicate?.let{x->AlertDialog(onDismissRequest=vm::dismiss,icon={AppStatusChip(stringResource(R.string.sales_duplicate_status),StatusTone.INFO)},title={Text(stringResource(R.string.sales_duplicate_title))},text={Column(verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){InfoRow(stringResource(R.string.sales_business_date),dateFmt.format(x.businessDate));InfoRow(stringResource(R.string.sales_imported_label),dateTimeFmt.format(x.importedAt))}},confirmButton={TextButton(onClick={vm.dismiss();onImport(x.exportId)}){Text(stringResource(R.string.sales_view_import))}},dismissButton={TextButton(onClick=vm::dismiss){Text(stringResource(R.string.action_cancel))}})}
 s.error?.let{e->AlertDialog(onDismissRequest=vm::dismiss,icon={AppStatusChip(stringResource(if(e.serious())R.string.sales_error_status else R.string.sales_attention_status),if(e.serious())StatusTone.ERROR else StatusTone.WARNING)},title={Text(stringResource(R.string.sales_import_problem))},text={Text(stringResource(e.message()))},confirmButton={TextButton(onClick=vm::dismiss){Text(stringResource(android.R.string.ok))}})}
}
@Composable private fun ImportButton(onClick:()->Unit,enabled:Boolean){AppPrimaryButton(onClick,enabled=enabled){Icon(Icons.Default.UploadFile,null);Spacer(Modifier.width(AppSpacing.sm));Text(stringResource(R.string.sales_import))}}
@Composable private fun EmptySales(action:()->Unit,enabled:Boolean){Column(Modifier.fillMaxWidth().padding(vertical=AppSpacing.xxl),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(AppSpacing.md)){Text(stringResource(R.string.sales_empty),style=MaterialTheme.typography.headlineSmall);Text(stringResource(R.string.sales_empty_body),color=MaterialTheme.colorScheme.onSurfaceVariant);ImportButton(action,enabled)}}
@Composable private fun BusyRow(){Row(Modifier.fillMaxWidth().padding(AppSpacing.sm),horizontalArrangement=Arrangement.Center,verticalAlignment=Alignment.CenterVertically){CircularProgressIndicator(Modifier.size(20.dp),strokeWidth=2.dp);Spacer(Modifier.width(AppSpacing.sm));Text(stringResource(R.string.sales_preparing),color=MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable private fun SalesHistoryCard(x:SalesImport,onClick:()->Unit){AppCard(Modifier.fillMaxWidth().clickable(onClick=onClick)){Column(Modifier.padding(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(dateFmt.format(x.businessDate),style=MaterialTheme.typography.titleMedium);Text(x.terminalId,style=MaterialTheme.typography.labelLarge)};Text(stringResource(R.string.sales_imported,dateTimeFmt.format(x.importedAt)),color=MaterialTheme.colorScheme.onSurfaceVariant);Text(stringResource(R.string.sales_revision_currency,x.publicationRevision,x.currency),color=MaterialTheme.colorScheme.onSurfaceVariant)}}}
@Composable private fun SalesImportPreview(x:PreparedSalesImport,busy:Boolean,dismiss:()->Unit,confirm:()->Unit){AlertDialog(onDismissRequest={if(!busy)dismiss()},title={Text(stringResource(R.string.sales_preview_title))},text={Column(verticalArrangement=Arrangement.spacedBy(AppSpacing.md)){PreviewSection(stringResource(R.string.sales_file_details),listOf(stringResource(R.string.sales_business_date) to dateFmt.format(x.businessDate),stringResource(R.string.sales_terminal_label) to x.terminalId,stringResource(R.string.sales_generated) to dateTimeFmt.format(x.generatedAt),stringResource(R.string.sales_revision_label) to x.publicationRevision.toString(),stringResource(R.string.sales_currency) to x.currency));PreviewSection(stringResource(R.string.sales_transactions),listOf(stringResource(R.string.sales_transaction_count) to x.transactionCount.toString(),stringResource(R.string.sales_completed) to x.completedCount.toString(),stringResource(R.string.sales_voided) to x.voidedCount.toString(),stringResource(R.string.sales_lines) to x.lineCount.toString()));PreviewSection(stringResource(R.string.sales_completed_sales),listOf(stringResource(R.string.sales_gross) to Formatters.formatCurrency(x.completedGross,x.currency),stringResource(R.string.sales_discounts) to Formatters.formatCurrency(x.completedDiscount,x.currency),stringResource(R.string.sales_net) to Formatters.formatCurrency(x.completedNet,x.currency)))}},confirmButton={AppPrimaryButton(confirm,enabled=!busy){if(busy){CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp);Spacer(Modifier.width(AppSpacing.sm))};Text(stringResource(if(busy)R.string.sales_importing else R.string.sales_import_action))}},dismissButton={TextButton(onClick=dismiss,enabled=!busy){Text(stringResource(R.string.action_cancel))}})}
@Composable private fun PreviewSection(title:String,rows:List<Pair<String,String>>){Column(verticalArrangement=Arrangement.spacedBy(AppSpacing.xs)){Text(title,style=MaterialTheme.typography.titleSmall);rows.forEach{InfoRow(it.first,it.second)}}}
@Composable private fun InfoRow(label:String,value:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.width(AppSpacing.md));Text(value)}}

@OptIn(ExperimentalMaterial3Api::class) @Composable fun SalesImportDetailRoute(onBack:()->Unit,onTransaction:(String,String)->Unit,vm:SalesImportDetailViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle()
 Scaffold(topBar={TopAppBar(title={Text(stringResource(R.string.sales_import_detail))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}})}){p->
  when{
   s.loading->Centered(p){CircularProgressIndicator()}
   s.error||s.detail==null->Centered(p){SalesErrorState(stringResource(R.string.sales_import_load_error),vm::retry)}
   else->BoxWithConstraints(Modifier.fillMaxSize().padding(p)){val d=s.detail!!;if(maxWidth>=760.dp)Row(Modifier.fillMaxSize().adaptiveContentWidth(1200.dp).padding(AppSpacing.md),horizontalArrangement=Arrangement.spacedBy(AppSpacing.lg)){Column(Modifier.width(340.dp),verticalArrangement=Arrangement.spacedBy(AppSpacing.lg)){SalesImportSummary(d.salesImport,s.summary!!);SalesAudit(d.salesImport)};TransactionList(d.transactions,onTransaction,Modifier.weight(1f))}else LazyColumn(Modifier.adaptiveContentWidth(760.dp),contentPadding=PaddingValues(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.lg)){item{SalesImportSummary(d.salesImport,s.summary!!)};item{AppSectionHeader(stringResource(R.string.sales_transactions))};items(d.transactions){x->TransactionRow(x){onTransaction(x.transaction.terminalId,x.transaction.transactionId)}};item{SalesAudit(d.salesImport)}}}
  }
 }
}
@Composable private fun SalesImportSummary(x:SalesImport,s:SalesSummary){Column(verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){AppSectionHeader(stringResource(R.string.sales_import_summary));Text(dateFmt.format(x.businessDate),style=MaterialTheme.typography.headlineSmall);Text(x.terminalId,style=MaterialTheme.typography.titleMedium);Text(stringResource(R.string.sales_imported,dateTimeFmt.format(x.importedAt)),color=MaterialTheme.colorScheme.onSurfaceVariant);Text(stringResource(R.string.sales_revision_currency,x.publicationRevision,x.currency),color=MaterialTheme.colorScheme.onSurfaceVariant);AppCard(Modifier.fillMaxWidth()){Column(Modifier.padding(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){Metric(stringResource(R.string.sales_completed),s.completed.toString());Metric(stringResource(R.string.sales_voided),s.voided.toString());Metric(stringResource(R.string.sales_transactions),s.transactions.toString());HorizontalDivider();Metric(stringResource(R.string.sales_gross),Formatters.formatCurrency(s.gross,x.currency));Metric(stringResource(R.string.sales_discounts),Formatters.formatCurrency(s.discount,x.currency));Metric(stringResource(R.string.sales_net),Formatters.formatCurrency(s.net,x.currency),true)}}}}
@Composable private fun Metric(label:String,value:String,strong:Boolean=false){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,style=if(strong)MaterialTheme.typography.titleMedium else MaterialTheme.typography.bodyLarge);Text(value,style=if(strong)MaterialTheme.typography.titleMedium else MaterialTheme.typography.bodyLarge)}}
@Composable private fun TransactionList(rows:List<ImportedSaleTransactionDetail>,open:(String,String)->Unit,modifier:Modifier){LazyColumn(modifier,verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){item{AppSectionHeader(stringResource(R.string.sales_transactions))};items(rows){x->TransactionRow(x){open(x.transaction.terminalId,x.transaction.transactionId)}}}}
@Composable private fun TransactionRow(d:ImportedSaleTransactionDetail,onClick:()->Unit){val x=d.transaction;AppCard(Modifier.fillMaxWidth().clickable(onClick=onClick)){Row(Modifier.padding(AppSpacing.md).fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(AppSpacing.md)){Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(AppSpacing.xs)){Text(timeFmt.format(x.openedAt),style=MaterialTheme.typography.titleMedium);AppStatusChip(status(x.status),if(x.status==ImportedSaleStatus.COMPLETED)StatusTone.SUCCESS else StatusTone.NEUTRAL);Text(stringResource(R.string.sales_line_count,d.lines.size),color=MaterialTheme.colorScheme.onSurfaceVariant)};Text(Formatters.formatCurrency(d.lines.fold(BigDecimal.ZERO){a,l->a+l.net},x.currency),style=MaterialTheme.typography.titleMedium)}}}
@Composable private fun SalesAudit(x:SalesImport){var open by remember{mutableStateOf(false)};Column(verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){OutlinedButton(onClick={open=!open}){Icon(if(open)Icons.Default.KeyboardArrowUp else Icons.Default.KeyboardArrowDown,null);Spacer(Modifier.width(AppSpacing.xs));Text(stringResource(R.string.sales_audit))};if(open)AppCard(Modifier.fillMaxWidth()){Column(Modifier.padding(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){InfoRow(stringResource(R.string.sales_export_id),x.exportId);InfoRow(stringResource(R.string.sales_sha256),x.originalSha256);InfoRow(stringResource(R.string.sales_menu_id),x.menuId)}}}}

@OptIn(ExperimentalMaterial3Api::class) @Composable fun SalesTransactionDetailRoute(onBack:()->Unit,vm:SalesTransactionDetailViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle()
 Scaffold(topBar={TopAppBar(title={Text(stringResource(R.string.sales_transaction))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}})}){p->
  when{
   s.loading->Centered(p){CircularProgressIndicator()}
   s.error||s.detail==null->Centered(p){SalesErrorState(stringResource(R.string.sales_transaction_load_error),vm::retry)}
   else->{val d=s.detail!!;val x=d.transaction;LazyColumn(Modifier.padding(p).adaptiveContentWidth(840.dp),contentPadding=PaddingValues(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.lg)){item{AppSectionHeader(stringResource(R.string.sales_transaction_overview));AppCard(Modifier.fillMaxWidth()){Column(Modifier.padding(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){AppStatusChip(status(x.status),if(x.status==ImportedSaleStatus.COMPLETED)StatusTone.SUCCESS else StatusTone.NEUTRAL);InfoRow(stringResource(R.string.sales_business_date),dateFmt.format(x.businessDate));InfoRow(stringResource(R.string.sales_opened),dateTimeFmt.format(x.openedAt));InfoRow(stringResource(R.string.sales_closed),dateTimeFmt.format(x.closedAt));InfoRow(stringResource(R.string.sales_terminal_label),x.terminalId);InfoRow(stringResource(R.string.sales_revision_label),x.publicationRevision.toString());InfoRow(stringResource(R.string.sales_currency),x.currency)}}};item{AppSectionHeader(stringResource(R.string.sales_sale_lines))};items(d.lines){SalesLine(it,x.currency)}}}
  }
 }
}
@Composable private fun SalesLine(l:ImportedSaleLine,currency:String){AppCard(Modifier.fillMaxWidth()){Column(Modifier.padding(AppSpacing.md),verticalArrangement=Arrangement.spacedBy(AppSpacing.sm)){Text(l.displayNameSnapshot,style=MaterialTheme.typography.titleMedium);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(stringResource(R.string.sales_quantity_price,Formatters.formatQuantity(l.quantity),Formatters.formatCurrency(l.unitPrice,currency)));Text(stringResource(R.string.sales_net_value,Formatters.formatCurrency(l.net,currency)),style=MaterialTheme.typography.titleMedium)};HorizontalDivider();InfoRow(stringResource(R.string.sales_gross),Formatters.formatCurrency(l.gross,currency));InfoRow(stringResource(R.string.sales_discounts),Formatters.formatCurrency(l.discount,currency))}}}
@Composable private fun SalesErrorState(message:String,retry:(()->Unit)?=null){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(AppSpacing.md)){Text(message,style=MaterialTheme.typography.titleMedium);retry?.let{Button(onClick=it){Text(stringResource(R.string.action_retry_desc))}}}}
@Composable private fun Centered(p:PaddingValues,content: @Composable () -> Unit){Box(Modifier.fillMaxSize().padding(p).padding(AppSpacing.lg),contentAlignment=Alignment.Center){content()}}
@Composable private fun status(s:ImportedSaleStatus)=stringResource(if(s==ImportedSaleStatus.COMPLETED)R.string.sales_completed else R.string.sales_voided)
private fun SalesUiError.serious()=this==SalesUiError.EXPORT_CONFLICT||this==SalesUiError.HISTORY_CONFLICT||this==SalesUiError.SAVE_FAILED
private fun SalesUiError.message()=when(this){SalesUiError.FILE_TOO_LARGE->R.string.sales_error_too_large;SalesUiError.UNREADABLE->R.string.sales_error_unreadable;SalesUiError.PERMISSION_DENIED->R.string.sales_error_permission;SalesUiError.INVALID_FILE->R.string.sales_error_invalid;SalesUiError.WRONG_RESTAURANT->R.string.sales_error_restaurant;SalesUiError.UNKNOWN_MENU->R.string.sales_error_unknown_menu;SalesUiError.MENU_MISMATCH->R.string.sales_error_menu_mismatch;SalesUiError.ITEM_MISMATCH->R.string.sales_error_item_mismatch;SalesUiError.EXPORT_CONFLICT->R.string.sales_error_export_conflict;SalesUiError.HISTORY_CONFLICT->R.string.sales_error_history_conflict;SalesUiError.SAVE_FAILED->R.string.sales_error_save}
