package com.miara.cuentame.feature.menu.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.miara.cuentame.R
import com.miara.cuentame.core.common.ids.MenuRecipeId
import com.miara.cuentame.core.designsystem.util.Formatters
import com.miara.cuentame.core.model.menu.*
import com.miara.cuentame.feature.menu.viewmodel.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun MenuCatalogListRoute(onBack:()->Unit,onOpen:(com.miara.cuentame.core.common.ids.MenuId)->Unit,vm:MenuCatalogListViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle();var create by remember{mutableStateOf(false)}
 LaunchedEffect(s.createdId){s.createdId?.let{create=false;vm.consumeCreated();onOpen(it)}}
 Scaffold(topBar={TopAppBar(title={Text(stringResource(R.string.catalog_menus))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}},actions={TextButton(onClick=vm::toggleArchived){Text(stringResource(if(s.includeArchived)R.string.catalog_hide_archived else R.string.menu_show_archived))}})},floatingActionButton={FloatingActionButton(onClick={create=true},modifier=Modifier.testTag("catalog_create")){Text("+")}}){p->
  when{ s.loading->Centered(p){CircularProgressIndicator()};s.loadError->Centered(p){Button(onClick=vm::retry){Text(stringResource(R.string.action_retry_desc))}};s.rows.isEmpty()->Centered(p){Column(horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(12.dp)){Text(stringResource(R.string.catalog_empty_title),style=MaterialTheme.typography.headlineSmall);Text(stringResource(R.string.catalog_empty_body));Button(onClick={create=true}){Text(stringResource(R.string.catalog_create))}}};else->LazyColumn(Modifier.padding(p).testTag("catalog_list"),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(s.rows,key={it.menu.id.value}){row->Card(Modifier.fillMaxWidth().clickable{onOpen(row.menu.id)}){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(4.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(row.menu.name,style=MaterialTheme.typography.titleMedium);if(row.menu.archivedAt!=null)Text(stringResource(R.string.catalog_archived))};Text(stringResource(R.string.catalog_counts,row.categoryCount,row.itemCount));Text(stringResource(R.string.catalog_default_discount,row.menu.defaultCashDiscountPercent.stripTrailingZeros().toPlainString()));if(row.menu.archivedAt!=null)TextButton(onClick={vm.setArchived(row.menu)},enabled=!s.busy){Text(stringResource(R.string.catalog_restore))}}}}}}
 }
 if(create)MenuCatalogDialog(null,s.busy,s.error,{create=false;vm.clearError()}){n,d,p->vm.create(n,d,p)}
}

@Composable private fun Centered(p:PaddingValues,content:@Composable () -> Unit)=Box(Modifier.fillMaxSize().padding(p).padding(24.dp),contentAlignment=Alignment.Center){content()}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun MenuCatalogDetailRoute(onBack:()->Unit,onOpenMenuItem:(MenuRecipeId)->Unit,vm:MenuCatalogDetailViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle();var editMenu by remember{mutableStateOf(false)};var categoryEdit by remember{mutableStateOf<MenuCategory?>(null)};var addCategory by remember{mutableStateOf(false)};var picker by remember{mutableStateOf<MenuCategory?>(null)};var deleteCategory by remember{mutableStateOf<MenuCategoryUiModel?>(null)};var removeItem by remember{mutableStateOf<MenuPlacementUiModel?>(null)};var moveItem by remember{mutableStateOf<MenuPlacementUiModel?>(null)}
 LaunchedEffect(s.busy,s.error){if(!s.busy&&s.error==null){if(editMenu)editMenu=false;if(addCategory||categoryEdit!=null){addCategory=false;categoryEdit=null}}}
 Scaffold(topBar={TopAppBar(title={Text(s.menu?.name?:stringResource(R.string.catalog_menu))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}},actions={if(s.menu!=null)TextButton(onClick={editMenu=true}){Text(stringResource(R.string.action_edit))}})}){p->when{ s.loading->Centered(p){CircularProgressIndicator()};s.loadError||s.menu==null->Centered(p){Text(stringResource(R.string.catalog_load_failed))};else->BoxWithConstraints(Modifier.fillMaxSize().padding(p)){val wide=maxWidth>=720.dp;if(wide)Row(Modifier.fillMaxSize()){MenuSummary(s.menu!!,{editMenu=true},vm::toggleArchived,s.busy,Modifier.width(280.dp).fillMaxHeight());CategoryList(s,{addCategory=true},{categoryEdit=it},{deleteCategory=it},{picker=it},{item->onOpenMenuItem(item.recipe.id)},{removeItem=it},{moveItem=it},vm::moveCategory,vm::moveItem,Modifier.weight(1f))}else LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{MenuSummary(s.menu!!,{editMenu=true},vm::toggleArchived,s.busy,Modifier.fillMaxWidth())};item{CategoryList(s,{addCategory=true},{categoryEdit=it},{deleteCategory=it},{picker=it},{item->onOpenMenuItem(item.recipe.id)},{removeItem=it},{moveItem=it},vm::moveCategory,vm::moveItem,Modifier.fillMaxWidth())}}}}
 }
 if(editMenu)s.menu?.let{MenuCatalogDialog(it,s.busy,s.error,{editMenu=false;vm.clearError()}){n,d,p->vm.updateMenu(n,d,p)}}
 if(addCategory||categoryEdit!=null)NameDialog(categoryEdit?.name.orEmpty(),s.busy,s.error,{addCategory=false;categoryEdit=null;vm.clearError()}){vm.saveCategory(categoryEdit,it)}
 picker?.let{ItemPicker(it,s.availableItems,s.currencyCode,s.busy,{picker=null}){recipe->vm.addItem(it,recipe)}}
 deleteCategory?.let{model->Confirm(stringResource(R.string.catalog_delete_category_title,model.category.name),stringResource(R.string.catalog_delete_category_body,model.items.size),s.busy,{deleteCategory=null}){vm.removeCategory(model.category);deleteCategory=null}}
 removeItem?.let{item->Confirm(stringResource(R.string.catalog_remove_item_title,item.recipe.name,s.menu?.name.orEmpty()),stringResource(R.string.catalog_remove_item_body),s.busy,{removeItem=null}){vm.removeItem(item);removeItem=null}}
 moveItem?.let{item->MoveDialog(item,s.categories.map{it.category},s.busy,{moveItem=null}){vm.moveItem(item,it);moveItem=null}}
}

@Composable private fun MenuSummary(menu:Menu,onEdit:()->Unit,onArchive:()->Unit,busy:Boolean,modifier:Modifier){Card(modifier.padding(16.dp)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(menu.name,style=MaterialTheme.typography.headlineSmall);menu.description?.let{Text(it)};Text(stringResource(R.string.catalog_default_discount,menu.defaultCashDiscountPercent.stripTrailingZeros().toPlainString()));Text(if(menu.publicationRevision==0L)stringResource(R.string.catalog_not_published)else stringResource(R.string.catalog_published_revision,menu.publicationRevision));OutlinedButton(onClick=onEdit){Text(stringResource(R.string.action_edit))};TextButton(onClick=onArchive,enabled=!busy){Text(stringResource(if(menu.archivedAt==null)R.string.catalog_archive else R.string.catalog_restore))}}}}
@Composable private fun CategoryList(s:MenuCatalogDetailState,onAdd:()->Unit,onEdit:(MenuCategory)->Unit,onDelete:(MenuCategoryUiModel)->Unit,onAddItem:(MenuCategory)->Unit,onOpen:(MenuPlacementUiModel)->Unit,onRemove:(MenuPlacementUiModel)->Unit,onMove:(MenuPlacementUiModel)->Unit,onMoveCategory:(Int,Int)->Unit,onMoveItem:(MenuCategoryUiModel,Int,Int)->Unit,modifier:Modifier){Column(modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text(stringResource(R.string.catalog_categories),style=MaterialTheme.typography.titleLarge);Button(onClick=onAdd,enabled=!s.busy){Text(stringResource(R.string.catalog_add_category))}};s.error?.let{Text(catalogError(it),color=MaterialTheme.colorScheme.error)};if(s.categories.isEmpty())Text(stringResource(R.string.catalog_no_categories));s.categories.forEachIndexed{ci,model->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(model.category.name,style=MaterialTheme.typography.titleMedium,modifier=Modifier.weight(1f));TextButton(onClick={onMoveCategory(ci,-1)},enabled=!s.busy&&ci>0){Text("↑")};TextButton(onClick={onMoveCategory(ci,1)},enabled=!s.busy&&ci<s.categories.lastIndex){Text("↓")};TextButton(onClick={onEdit(model.category)}){Text(stringResource(R.string.action_edit))};TextButton(onClick={onDelete(model)}){Text(stringResource(R.string.action_delete))}};model.items.forEachIndexed{ii,item->Row(Modifier.fillMaxWidth().clickable{onOpen(item)}.padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.recipe.name);if(item.recipe.archivedAt!=null)Text(stringResource(R.string.catalog_item_archived),style=MaterialTheme.typography.labelSmall)};Text(item.recipe.sellingPrice?.let{Formatters.formatCurrency(it,s.currencyCode)}?:stringResource(R.string.menu_selling_not_set));TextButton(onClick={onMoveItem(model,ii,-1)},enabled=!s.busy&&ii>0){Text("↑")};TextButton(onClick={onMoveItem(model,ii,1)},enabled=!s.busy&&ii<model.items.lastIndex){Text("↓")};TextButton(onClick={onMove(item)}){Text(stringResource(R.string.catalog_move))};TextButton(onClick={onRemove(item)}){Text(stringResource(R.string.catalog_remove))}}};TextButton(onClick={onAddItem(model.category)},enabled=!s.busy){Text(stringResource(R.string.catalog_add_item))}}}}}}

@Composable private fun MenuCatalogDialog(menu:Menu?,busy:Boolean,error:MenuCatalogUiError?,dismiss:()->Unit,save:(String,String,String)->Unit){var n by remember(menu){mutableStateOf(menu?.name.orEmpty())};var d by remember(menu){mutableStateOf(menu?.description.orEmpty())};var p by remember(menu){mutableStateOf(menu?.defaultCashDiscountPercent?.toPlainString()?:"0")};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(if(menu==null)R.string.catalog_create else R.string.catalog_edit))},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(n,{n=it},label={Text(stringResource(R.string.menu_name))});OutlinedTextField(d,{d=it},label={Text(stringResource(R.string.catalog_description))});OutlinedTextField(p,{p=it},label={Text(stringResource(R.string.catalog_discount_percent))});error?.let{Text(catalogError(it),color=MaterialTheme.colorScheme.error)}}},confirmButton={Button(onClick={save(n,d,p)},enabled=!busy&&n.isNotBlank()){Text(stringResource(R.string.action_save))}},dismissButton={TextButton(onClick=dismiss,enabled=!busy){Text(stringResource(R.string.action_cancel))}})}
@Composable private fun NameDialog(initial:String,busy:Boolean,error:MenuCatalogUiError?,dismiss:()->Unit,save:(String)->Unit){var n by remember{mutableStateOf(initial)};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.catalog_category_name))},text={Column{OutlinedTextField(n,{n=it},label={Text(stringResource(R.string.menu_name))});error?.let{Text(catalogError(it),color=MaterialTheme.colorScheme.error)}}},confirmButton={Button(onClick={save(n)},enabled=!busy&&n.isNotBlank()){Text(stringResource(R.string.action_save))}},dismissButton={TextButton(onClick=dismiss){Text(stringResource(R.string.action_cancel))}})}
@Composable private fun ItemPicker(category:MenuCategory,items:List<MenuRecipe>,currencyCode:String,busy:Boolean,dismiss:()->Unit,select:(MenuRecipe)->Unit){var q by remember{mutableStateOf("")};val shown=items.filter{it.name.contains(q,true)};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.catalog_add_to,category.name))},text={Column{OutlinedTextField(q,{q=it},label={Text(stringResource(R.string.catalog_search_items))},modifier=Modifier.testTag("catalog_item_search"));LazyColumn(Modifier.heightIn(max=360.dp)){items(shown,key={it.id.value}){r->ListItem(headlineContent={Text(r.name)},trailingContent={Text(r.sellingPrice?.let{Formatters.formatCurrency(it,currencyCode)}.orEmpty())},modifier=Modifier.clickable(enabled=!busy){select(r)})}};if(shown.isEmpty())Text(stringResource(R.string.catalog_no_available_items))}},confirmButton={},dismissButton={TextButton(onClick=dismiss){Text(stringResource(R.string.action_cancel))}})}
@Composable private fun Confirm(title:String,body:String,busy:Boolean,dismiss:()->Unit,confirm:()->Unit)=AlertDialog(onDismissRequest=dismiss,title={Text(title)},text={Text(body)},confirmButton={Button(onClick=confirm,enabled=!busy){Text(stringResource(R.string.action_delete))}},dismissButton={TextButton(onClick=dismiss){Text(stringResource(R.string.action_cancel))}})
@Composable private fun MoveDialog(item:MenuPlacementUiModel,categories:List<MenuCategory>,busy:Boolean,dismiss:()->Unit,move:(MenuCategory)->Unit)=AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.catalog_move_item,item.recipe.name))},text={Column{categories.filter{it.id!=item.placement.categoryId}.forEach{c->TextButton(onClick={move(c)},enabled=!busy){Text(c.name)}}}},confirmButton={},dismissButton={TextButton(onClick=dismiss){Text(stringResource(R.string.action_cancel))}})
@Composable private fun catalogError(e:MenuCatalogUiError)=stringResource(when(e){MenuCatalogUiError.INVALID_VALUES->R.string.catalog_error_invalid;MenuCatalogUiError.DUPLICATE_MENU_NAME->R.string.catalog_error_duplicate_menu;MenuCatalogUiError.DUPLICATE_CATEGORY_NAME->R.string.catalog_error_duplicate_category;MenuCatalogUiError.ITEM_ALREADY_IN_MENU->R.string.catalog_error_duplicate_item;MenuCatalogUiError.OWNERSHIP_ERROR->R.string.catalog_error_ownership;MenuCatalogUiError.SAVE_FAILED->R.string.menu_error_save_failed})
