package com.miara.cuentame.feature.menu.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.miara.cuentame.R
import com.miara.cuentame.core.common.ids.MenuRecipeId
import com.miara.cuentame.core.common.ids.IngredientId
import com.miara.cuentame.core.designsystem.util.Formatters
import com.miara.cuentame.core.model.menu.*
import com.miara.cuentame.feature.menu.viewmodel.*

@OptIn(ExperimentalMaterial3Api::class) @Composable fun MenuListRoute(onBack:()->Unit,onOpen:(MenuRecipeId)->Unit,vm:MenuListViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle(); var create by remember{mutableStateOf(false)}
 Scaffold(topBar={TopAppBar(title={Text(stringResource(R.string.menu_items_title))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}},actions={TextButton(onClick=vm::toggleArchived){Text(stringResource(R.string.menu_show_archived))}})},floatingActionButton={FloatingActionButton(onClick={create=true},modifier=Modifier.testTag("menu_create")){Text("+")}}){p->
  when{ s.loading->Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){CircularProgressIndicator()};s.error->Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){Button(onClick=vm::retry){Text(stringResource(R.string.action_retry_desc))}};s.rows.isEmpty()->Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){Text(stringResource(R.string.menu_empty))};else->LazyColumn(Modifier.padding(p).testTag("menu_list")){items(s.rows,key={it.first.id.value}){(r,c)->ListItem(headlineContent={Text(r.name)},supportingContent={Column{Text(r.sellingPrice?.let{Formatters.formatCurrency(it,c?.currencyCode?:"USD")}?:stringResource(R.string.menu_selling_not_set));CostSummary(c)}},modifier=Modifier.clickable{onOpen(r.id)});HorizontalDivider()}}}
 }
 if(create) MenuEditDialog(stringResource(R.string.menu_create_title),"","",{create=false}){n,p->vm.create(n,p){create=false;onOpen(it)}}
}

@Composable private fun CostSummary(c:MenuRecipeCost?){if(c==null)return;when(c.status){MenuRecipeCostStatus.FULLY_COSTED->Text(stringResource(R.string.menu_plate_and_food_cost,Formatters.formatCurrency(c.currentPlateCost!!,c.currencyCode),c.sellingMetrics.foodCostPercent?.let(Formatters::formatPercent)?:stringResource(R.string.menu_unavailable)));MenuRecipeCostStatus.PARTIALLY_COSTED->Text(stringResource(R.string.menu_partially_costed,c.costedComponentCount,c.componentCount));MenuRecipeCostStatus.UNCOSTED->Text(stringResource(R.string.menu_uncosted))}}

@OptIn(ExperimentalMaterial3Api::class) @Composable fun MenuDetailRoute(onBack:()->Unit,vm:MenuDetailViewModel=hiltViewModel()){
 val s by vm.state.collectAsStateWithLifecycle();var edit by remember{mutableStateOf(false)};var adding by remember{mutableStateOf(false)};var componentEdit by remember{mutableStateOf<MenuRecipeComponent?>(null)};val r=s.recipe;val c=s.cost
 Scaffold(topBar={TopAppBar(title={Text(r?.name?:stringResource(R.string.menu_item_title))},navigationIcon={TextButton(onClick=onBack){Text(stringResource(R.string.action_back))}},actions={if(r!=null)TextButton(onClick={edit=true}){Text(stringResource(R.string.action_edit))}})}){p->if(s.loading)Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){CircularProgressIndicator()}else if(r!=null&&c!=null)LazyColumn(Modifier.padding(p).padding(16.dp).testTag("menu_detail"),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text(stringResource(R.string.menu_basic_info),style=MaterialTheme.typography.titleMedium);Text(r.sellingPrice?.let{Formatters.formatCurrency(it,c.currencyCode)}?:stringResource(R.string.menu_selling_not_set))};item{Text(stringResource(R.string.menu_current_cost),style=MaterialTheme.typography.titleMedium);CostDetail(c)};item{Text(stringResource(R.string.menu_components),style=MaterialTheme.typography.titleMedium);Button(onClick={adding=true},modifier=Modifier.testTag("menu_add_component")){Text(stringResource(R.string.menu_add_component))}};items(c.components){x->Card(Modifier.fillMaxWidth().clickable{componentEdit=s.components.firstOrNull{it.id==x.componentId}}){Column(Modifier.padding(12.dp)){Text(x.ingredientName);Text("${Formatters.formatQuantity(x.quantityEntered)} ${x.enteredUnitLabel.orEmpty()}");Text(if(x.source==MenuCostSource.ACTIVE_PREPARATION_RECIPE)stringResource(R.string.menu_source_preparation) else stringResource(R.string.menu_source_raw));Text(x.currentCost?.let{Formatters.formatCurrency(it,c.currencyCode)}?:missingLabel(x.missingReason))}}};item{OutlinedButton(onClick=vm::archive){Text(if(r.archivedAt==null)stringResource(R.string.menu_archive) else stringResource(R.string.menu_restore))}}}}
 if(edit&&r!=null)MenuEditDialog(stringResource(R.string.action_edit),r.name,r.sellingPrice?.toPlainString().orEmpty(),{edit=false}){n,p->vm.save(n,p);edit=false}
 if(adding)ComponentDialog(null,s.ingredients,{adding=false},{ingredient,quantity->vm.saveComponent(null,ingredient,quantity);adding=false},null)
 componentEdit?.let{existing->ComponentDialog(existing,s.ingredients,{componentEdit=null},{ingredient,quantity->vm.saveComponent(existing,ingredient,quantity);componentEdit=null},{vm.removeComponent(existing);componentEdit=null})}
}
@Composable private fun CostDetail(c:MenuRecipeCost){when(c.status){MenuRecipeCostStatus.FULLY_COSTED->{Text(stringResource(R.string.menu_plate_cost,Formatters.formatCurrency(c.currentPlateCost!!,c.currencyCode)),Modifier.testTag("plate_cost"));Text(c.sellingMetrics.foodCostPercent?.let{stringResource(R.string.menu_food_cost,Formatters.formatPercent(it))}?:stringResource(R.string.menu_food_cost_unavailable));Text(c.sellingMetrics.grossProfitBeforeLaborAndOverhead?.let{stringResource(R.string.menu_gross_profit,Formatters.formatCurrency(it,c.currencyCode))}?:stringResource(R.string.menu_gross_profit_unavailable))};MenuRecipeCostStatus.PARTIALLY_COSTED->{Text(stringResource(R.string.menu_partially_costed,c.costedComponentCount,c.componentCount));Text(stringResource(R.string.menu_known_subtotal,Formatters.formatCurrency(c.knownCostSubtotal,c.currencyCode)),Modifier.testTag("known_subtotal"));Text(stringResource(R.string.menu_food_cost_unavailable));Text(stringResource(R.string.menu_gross_profit_unavailable))};MenuRecipeCostStatus.UNCOSTED->Text(stringResource(R.string.menu_uncosted))};if(c.priceImpact.coveredLeafCount>0)Text(stringResource(R.string.menu_vendor_impact,Formatters.formatCurrency(c.priceImpact.knownSubtotal,c.currencyCode),c.priceImpact.coveredLeafCount,c.priceImpact.totalLeafCount))}
@Composable private fun missingLabel(r:MenuRecipeCostMissingReason?)=when(r){MenuRecipeCostMissingReason.INGREDIENT_COST_MISSING->stringResource(R.string.menu_missing_cost);MenuRecipeCostMissingReason.INGREDIENT_COST_INVALID->stringResource(R.string.menu_invalid_cost);MenuRecipeCostMissingReason.ACTIVE_PREPARATION_PARTIAL->stringResource(R.string.menu_preparation_partial);MenuRecipeCostMissingReason.ACTIVE_PREPARATION_UNCOSTED->stringResource(R.string.menu_preparation_uncosted);MenuRecipeCostMissingReason.ACTIVE_PREPARATION_YIELD_UNAVAILABLE->stringResource(R.string.menu_preparation_yield_missing);MenuRecipeCostMissingReason.PREPARATION_DEPENDENCY_CYCLE->stringResource(R.string.menu_preparation_cycle);null->stringResource(R.string.menu_unavailable)}
@Composable private fun MenuEditDialog(title:String,initialName:String,initialPrice:String,onDismiss:()->Unit,onSave:(String,String)->Unit){var n by remember{mutableStateOf(initialName)};var p by remember{mutableStateOf(initialPrice)};AlertDialog(onDismissRequest=onDismiss,title={Text(title)},text={Column{OutlinedTextField(n,{n=it},label={Text(stringResource(R.string.menu_name))});OutlinedTextField(p,{p=it},label={Text(stringResource(R.string.menu_selling_price))})}},confirmButton={Button(onClick={onSave(n,p)},enabled=n.isNotBlank()&&(p.isBlank()||p.toBigDecimalOrNull()?.let{it>=java.math.BigDecimal.ZERO}==true)){Text(stringResource(R.string.action_save))}},dismissButton={TextButton(onClick=onDismiss){Text(stringResource(R.string.action_cancel))}})}
@Composable private fun ComponentDialog(existing:MenuRecipeComponent?,ingredients:List<com.miara.cuentame.core.model.ingredient.Ingredient>,onDismiss:()->Unit,onSave:(IngredientId,String)->Unit,onDelete:(()->Unit)?){var selected by remember{mutableStateOf(existing?.ingredientId?:ingredients.firstOrNull()?.id)};var quantity by remember{mutableStateOf(existing?.quantityEntered?.toPlainString().orEmpty())};var expanded by remember{mutableStateOf(false)};AlertDialog(onDismissRequest=onDismiss,title={Text(stringResource(if(existing==null)R.string.menu_add_component else R.string.menu_edit_component))},text={Column{Box{OutlinedButton(onClick={expanded=true}){Text(ingredients.firstOrNull{it.id==selected}?.name?:stringResource(R.string.menu_choose_ingredient))};DropdownMenu(expanded,onDismissRequest={expanded=false}){ingredients.forEach{i->DropdownMenuItem(text={Text(i.name)},onClick={selected=i.id;expanded=false})}}};OutlinedTextField(quantity,{quantity=it},label={Text(stringResource(R.string.menu_quantity))});if(onDelete!=null)TextButton(onClick=onDelete){Text(stringResource(R.string.menu_remove_component))}}},confirmButton={Button(onClick={selected?.let{onSave(it,quantity)}},enabled=selected!=null&&quantity.toBigDecimalOrNull()?.let{it>java.math.BigDecimal.ZERO}==true){Text(stringResource(R.string.action_save))}},dismissButton={TextButton(onClick=onDismiss){Text(stringResource(R.string.action_cancel))}})}
