package com.venkoi.cuentame.core.database.backup

import com.venkoi.cuentame.core.database.entity.*

data class BackupSnapshot(
    val restaurants: List<RestaurantEntity>,
    val inventoryAreas: List<InventoryAreaEntity>,
    val ingredientCategories: List<IngredientCategoryEntity>,
    val units: List<UnitEntity>,
    val ingredients: List<IngredientEntity>,
    val ingredientUnitOptions: List<IngredientUnitOptionEntity>,
    val suppliers: List<SupplierEntity>,
    val purchaseReceipts: List<PurchaseReceiptEntity>,
    val purchaseLines: List<PurchaseLineEntity>,
    val stockCounts: List<StockCountEntity>,
    val stockCountAreas: List<StockCountAreaEntity>,
    val stockCountLines: List<StockCountLineEntity>,
    val wasteEvents: List<WasteEventEntity>,
    val inventoryMovements: List<InventoryMovementEntity>,
    val inventoryBalanceProjections: List<InventoryBalanceProjectionEntity>,
    val ingredientCostProjections: List<IngredientCostProjectionEntity>,
    val preparationRecipes: List<PreparationRecipeEntity>,
    val preparationRecipeComponents: List<PreparationRecipeComponentEntity>,
    val productionBatches: List<ProductionBatchEntity>,
    val productionBatchComponents: List<ProductionBatchComponentEntity>,
    val purchaseInvoiceOcrResults: List<PurchaseInvoiceOcrResultEntity> = emptyList(),
    val purchaseInvoiceOcrPages: List<PurchaseInvoiceOcrPageEntity> = emptyList(),
    val purchaseInvoiceParseResults: List<PurchaseInvoiceParseResultEntity> = emptyList(),
    val purchaseInvoiceParsedLines: List<PurchaseInvoiceParsedLineEntity> = emptyList(),
    val supplierItemMappings: List<SupplierItemMappingEntity> = emptyList(),
    val purchaseInvoiceLineMatches: List<PurchaseInvoiceLineMatchEntity> = emptyList(),
    val purchaseInvoiceDraftApplications: List<PurchaseInvoiceDraftApplicationEntity> = emptyList(),
    val purchaseInvoiceLineOrigins: List<PurchaseInvoiceLineOriginEntity> = emptyList(),
    val stockCountItemOrder: List<StockCountItemOrderEntity> = emptyList(),
    val menuRecipes: List<MenuRecipeEntity> = emptyList(),
    val menuRecipeComponents: List<MenuRecipeComponentEntity> = emptyList(),
    val menus: List<MenuEntity> = emptyList(),
    val menuCategories: List<MenuCategoryEntity> = emptyList(),
    val menuPlacements: List<MenuPlacementEntity> = emptyList(),
    val menuPublications: List<MenuPublicationEntity> = emptyList(),
    val menuPublicationCategories: List<MenuPublicationCategoryEntity> = emptyList(),
    val menuPublicationItems: List<MenuPublicationItemEntity> = emptyList(),
    val menuPublicationItemComponents: List<MenuPublicationItemComponentEntity> = emptyList(),
    val salesImports:List<SalesImportEntity> = emptyList(),
    val importedSaleTransactions:List<ImportedSaleTransactionEntity> = emptyList(),
    val importedSaleLines:List<ImportedSaleLineEntity> = emptyList(),
    val salesImportTransactionRefs:List<SalesImportTransactionRefEntity> = emptyList()
)
