package com.venkoi.cuentame.core.database.repository

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import com.google.common.truth.Truth.assertThat
import com.venkoi.cuentame.core.common.ids.*
import com.venkoi.cuentame.core.database.RestaurantInventoryDatabase
import com.venkoi.cuentame.core.database.entity.*
import com.venkoi.cuentame.core.domain.repository.*
import com.venkoi.cuentame.core.domain.service.MenuCostCalculator
import com.venkoi.cuentame.core.model.ingredient.*
import com.venkoi.cuentame.core.model.menu.CashDiscountBehavior
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.runBlocking
import org.junit.*
import org.junit.runner.RunWith
import java.math.BigDecimal

@RunWith(AndroidJUnit4::class)
class RoomMenuRecipeRepositoryTest {
 private lateinit var db:RestaurantInventoryDatabase;private lateinit var definitions:RoomMenuRecipeRepository;private lateinit var costs:RoomMenuCostRepository
 private val restaurant=RestaurantId("r1")
 @Before fun setup()=runBlocking{db=Room.inMemoryDatabaseBuilder(ApplicationProvider.getApplicationContext<Context>(),RestaurantInventoryDatabase::class.java).allowMainThreadQueries().build();db.restaurantDao().insert(RestaurantEntity("r1","R","USD","en-US",0,0,null));db.unitDao().insertSeedUnits(listOf(UnitEntity("u","Unit","u","COUNT",BigDecimal.ONE,true,0)));ingredient("i1","Beef",BigDecimal("2"));definitions=RoomMenuRecipeRepository(db,db.menuRecipeDao(),db.ingredientDao(),db.ingredientUnitOptionDao());val prep=object:PreparationCostRepository{override fun observeRecipeCost(recipeId:PreparationRecipeId)=flowOf(null);override fun observeRecipeCostSummaries(restaurantId:RestaurantId)=flowOf(emptyList<PreparationRecipeCostSummary>());override fun observeActivePreparationCostsByOutput(restaurantId:RestaurantId)=flowOf(emptyMap<IngredientId,PreparationRecipeCost>())};val prices=object:PriceIntelligenceRepository{override fun observeIngredientPriceHistory(ingredientId:IngredientId)=flow<IngredientPriceHistory>{error("unused")};override fun observeLargePriceIncreases()=flowOf(emptyList<PriceIncreaseAlert>());override fun observePriceComparisons(restaurantId:RestaurantId,ingredientIds:Set<IngredientId>)=flowOf(emptyMap<IngredientId,VendorPriceComparison>())};costs=RoomMenuCostRepository(db.menuRecipeDao(),db.ingredientDao(),db.ingredientUnitOptionDao(),db.ingredientCostProjectionDao(),db.unitDao(),db.restaurantDao(),prep,prices,MenuCostCalculator())}
 @After fun close()=db.close()
 @Test fun persistedBaseQuantityAndRawCostAreReactiveWithoutInventoryMutation()=runBlocking{val id=definitions.create(restaurant,"Burger",BigDecimal("10"),null);definitions.saveComponent(id,null,IngredientId("i1"),IngredientUnitOptionId("i1-opt"),BigDecimal("2"),0);assertThat(definitions.observeComponents(id).first().single().quantityBase.compareTo(BigDecimal("4"))).isEqualTo(0);costs.observeCost(id).test{var c=awaitItem()!!;assertThat(c.currentPlateCost!!.compareTo(BigDecimal("8"))).isEqualTo(0);db.ingredientUnitOptionDao().upsert(option("i1",BigDecimal("99")));assertThat(definitions.observeComponents(id).first().single().quantityBase.compareTo(BigDecimal("4"))).isEqualTo(0);db.ingredientCostProjectionDao().upsert(IngredientCostProjectionEntity("r1","i1","3",1));do{c=awaitItem()!!}while(c.currentPlateCost?.compareTo(BigDecimal("12"))!=0);assertThat(c.currentPlateCost!!.compareTo(BigDecimal("12"))).isEqualTo(0);cancelAndIgnoreRemainingEvents()};assertThat(db.backupDao().getAllInventoryMovements()).isEmpty()}
 @Test fun explicitlySelectedUnitControlsCanonicalQuantityAndCost()=runBlocking{db.ingredientUnitOptionDao().insert(IngredientUnitOptionEntity("i1-oz","i1","Ounce","oz","u",BigDecimal("0.0625"),false,false,false,true,0,0,null));val id=definitions.create(restaurant,"Steak",null,null);definitions.saveComponent(id,null,IngredientId("i1"),IngredientUnitOptionId("i1-oz"),BigDecimal("8"),0);var component=definitions.observeComponents(id).first().single();assertThat(component.ingredientUnitOptionId).isEqualTo(IngredientUnitOptionId("i1-oz"));assertThat(component.quantityEntered.compareTo(BigDecimal("8"))).isEqualTo(0);assertThat(component.quantityBase.compareTo(BigDecimal("0.5"))).isEqualTo(0);assertThat(costs.observeCost(id).first()!!.currentPlateCost!!.compareTo(BigDecimal("1.0"))).isEqualTo(0);definitions.saveComponent(id,component.id,IngredientId("i1"),IngredientUnitOptionId("i1-opt"),BigDecimal.ONE,0);component=definitions.observeComponents(id).first().single();assertThat(component.quantityBase.compareTo(BigDecimal("2"))).isEqualTo(0);assertThat(costs.observeCost(id).first()!!.currentPlateCost!!.compareTo(BigDecimal("4"))).isEqualTo(0)}
 @Test(expected=MenuRecipeValidationException.OwnershipMismatch::class) fun rejectsCrossRestaurantIngredient()=runBlocking{db.restaurantDao().insert(RestaurantEntity("r2","Other","USD","en-US",0,0,null));db.ingredientDao().insert(IngredientEntity("other","r2","Other","other",null,"u",null,null,null,null,true,0,0,null));db.ingredientUnitOptionDao().insert(option("other",BigDecimal.ONE));val id=definitions.create(restaurant,"Burger",null,null);definitions.saveComponent(id,null,IngredientId("other"),IngredientUnitOptionId("other-opt"),BigDecimal.ONE,0);Unit}
 @Test fun commercialRevisionUsesSemanticPriceEqualityAndBehaviorChanges()=runBlocking{val id=definitions.create(restaurant,"Burger",BigDecimal("10"),null);assertThat(definitions.observeRecipe(id).first()!!.commercialRevision).isEqualTo(0);definitions.update(id,"Burger",BigDecimal("11.0"),null);assertThat(definitions.observeRecipe(id).first()!!.commercialRevision).isEqualTo(1);definitions.update(id,"Renamed",BigDecimal("11.00"),"note");assertThat(definitions.observeRecipe(id).first()!!.commercialRevision).isEqualTo(1);definitions.setCashDiscountBehavior(id,CashDiscountBehavior.NONE);assertThat(definitions.observeRecipe(id).first()!!.commercialRevision).isEqualTo(2);definitions.setCashDiscountBehavior(id,CashDiscountBehavior.NONE);definitions.setArchived(id,true);definitions.setArchived(id,false);assertThat(definitions.observeRecipe(id).first()!!.commercialRevision).isEqualTo(2)}
 @Test fun consumptionRevisionTracksSemanticsOnlyAndRealDeletion()=runBlocking{ingredient("i2","Cheese",BigDecimal.ONE);ingredient("i3","Sauce",BigDecimal.ONE);db.ingredientUnitOptionDao().insert(IngredientUnitOptionEntity("i1-alt","i1","Alt","a","u",BigDecimal.ONE,true,false,false,true,0,0,null));val id=definitions.create(restaurant,"Burger",null,null);val c1=definitions.saveComponent(id,null,IngredientId("i1"),IngredientUnitOptionId("i1-opt"),BigDecimal("1.0"),0);assertThat(revision(id)).isEqualTo(1);val c2=definitions.saveComponent(id,null,IngredientId("i2"),IngredientUnitOptionId("i2-opt"),BigDecimal.ONE,1);assertThat(revision(id)).isEqualTo(2);definitions.saveComponent(id,c1,IngredientId("i1"),IngredientUnitOptionId("i1-opt"),BigDecimal("2"),0);assertThat(revision(id)).isEqualTo(3);definitions.saveComponent(id,c1,IngredientId("i1"),IngredientUnitOptionId("i1-alt"),BigDecimal("4"),0);assertThat(revision(id)).isEqualTo(4);definitions.saveComponent(id,c1,IngredientId("i3"),IngredientUnitOptionId("i3-opt"),BigDecimal("2"),0);assertThat(revision(id)).isEqualTo(5);definitions.saveComponent(id,c1,IngredientId("i3"),IngredientUnitOptionId("i3-opt"),BigDecimal("2.00"),9);assertThat(revision(id)).isEqualTo(5);definitions.removeComponent(id,c2);assertThat(revision(id)).isEqualTo(6);definitions.removeComponent(id,MenuRecipeComponentId("missing"));assertThat(revision(id)).isEqualTo(6);try{definitions.saveComponent(id,c1,IngredientId("missing"),IngredientUnitOptionId("i1-alt"),BigDecimal.ONE,0)}catch(_:MenuRecipeValidationException){};assertThat(revision(id)).isEqualTo(6)}
 private suspend fun revision(id:MenuRecipeId)=definitions.observeRecipe(id).first()!!.consumptionRevision
 private suspend fun ingredient(id:String,name:String,cost:BigDecimal){db.ingredientDao().insert(IngredientEntity(id,"r1",name,name.lowercase(),null,"u",null,null,null,null,true,0,0,null));db.ingredientUnitOptionDao().insert(option(id,BigDecimal("2")));db.ingredientCostProjectionDao().upsert(IngredientCostProjectionEntity("r1",id,cost.toPlainString(),0))}
 private fun option(id:String,factor:BigDecimal)=IngredientUnitOptionEntity("$id-opt",id,"unit","u","u",factor,true,true,true,true,0,0,null)
}
